export const SET_NUTRITION_DATA = "SET_NUTRITION_DATA";
export const RESET_DATA = "RESET_DATA";
export const ADD_NEW_ITEM = "ADD_NEW_ITEM";
export const SET_NUM_ROWS_SELECTED = "SET_NUM_ROWS_SELECTED";
